version: '3.8'

volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${PGUSER}           # Retrieved from your environment configuration
      - POSTGRES_PASSWORD=${PGPASSWORD}   # Retrieved from your environment configuration
      - POSTGRES_DB=${PGDATABASE}         # Retrieved from your environment configuration
      - POSTGRES_NON_ROOT_USER=${PGUSER}  # Retrieved from your environment configuration
      - POSTGRES_NON_ROOT_PASSWORD=${PGPASSWORD}  # Retrieved from your environment configuration
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${PGUSER} -d ${PGDATABASE}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${PGDATABASE}
      - DB_POSTGRESDB_USER=${PGUSER}
      - DB_POSTGRESDB_PASSWORD=${PGPASSWORD}
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
